version: '2.0'

services:

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    # restart: none
    privileged: true
    network_mode: host # required to read main interface MAC instead of virtual one
    environment:
      GATEWAY_EUI: 0242ACFFFE110002
      MODEL: "SX1301"
      TC_KEY: <REPLACE-ME>
      TC_URI: <REPLACE-ME>
      DEVICE: /dev/spidev0.0
      INTERFACE: SPI
      SPI_SPEED: 200000
      USE_LIBGPIOD: 1
      GPIO_CHIP: gpiochip4
      RESET_GPIO: 22
