name: $SNAP_INSTANCE_NAME

services:
  basicstation:
    image: xoseperez/basicstation:$DOCKER_IMAGE_TAG
    logging:
      driver: none
    network_mode: host # required to read host interface MAC instead of virtual one, you don't need this if you set the GATEWAY_EUI manually

    devices:
      - "${spi_device:-/dev/spidev0.0}"
      - "/dev/${gpio_chip:-gpiochip0}"

    env_file: $SNAP_COMMON/conf.env
  