name: lora-basicstation
base: core24
version: &VERSION v2.8.3
summary: LoRa Basics™ Station - The LoRaWAN Gateway Software
description: |
  This snap bundles the lora-basicstation docker container into a snap.

grade: devel
confinement: strict

environment:
  PATH: $SNAP/docker/bin:$PATH
  DOCKER_IMAGE_TAG: *VERSION

plugs:
  docker-executables:
    interface: content
    content: docker-executables
    target: $SNAP/docker
    default-provider: docker
  docker:
    label: Access to the Docker Engine's unix socket
    default-provider: docker

parts:
  local:
    plugin: dump
    source: snap/local

apps:
  lora-basicstation:
    command: bin/run.sh
    daemon: simple
